// Script para regenerar temp-db.json con datos de prueba
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');

const dbPath = path.join(__dirname, '../temp-db.json');

async function regenerateDB() {
  console.log('🔄 Regenerando base de datos temporal...\n');

  const hashedPassword = await bcrypt.hash('password123', 10);

  const db = {
    users: [
      {
        id: 'admin-001',
        email: 'admin@mipage.cl',
        password: hashedPassword,
        name: 'Administrador MiPage',
        role: 'ADMIN',
        isVerified: true,
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
        isActive: true,
        approvalStatus: 'ACTIVE',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'publisher-001',
        email: 'maria@example.com',
        password: hashedPassword,
        name: 'María González',
        role: 'PUBLISHER',
        isVerified: true,
        bio: 'Modelo profesional con 5 años de experiencia en moda y publicidad. Especializada en fotografía editorial y comercial.',
        phone: '+56912345678',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
        isActive: true,
        approvalStatus: 'ACTIVE',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'publisher-002',
        email: 'carlos@example.com',
        password: hashedPassword,
        name: 'Carlos Rodríguez',
        role: 'PUBLISHER',
        isVerified: true,
        bio: 'Masajista certificado con 8 años de experiencia. Especializado en masajes terapéuticos y deportivos.',
        phone: '+56987654321',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
        isActive: true,
        approvalStatus: 'ACTIVE',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'publisher-003',
        email: 'sofia@example.com',
        password: hashedPassword,
        name: 'Sofía Martínez',
        role: 'PUBLISHER',
        isVerified: true,
        bio: 'Modelo y fotógrafa profesional. Me encanta capturar momentos únicos.',
        phone: '+56955555555',
        avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200',
        isActive: false,
        approvalStatus: 'PENDING',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'user-001',
        email: 'juan@example.com',
        password: hashedPassword,
        name: 'Juan Pérez',
        role: 'USER',
        isVerified: true,
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=juan',
        isActive: true,
        approvalStatus: 'ACTIVE',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    services: [
      {
        id: 'service-001',
        userId: 'publisher-001',
        category: 'MODELAJE',
        title: 'Sesión Fotográfica Profesional',
        description: 'Sesión fotográfica profesional para moda, catálogos y redes sociales. Incluye maquillaje básico, vestuario y edición de fotos.',
        price: 75000,
        priceType: 'session',
        location: 'Estudio Providencia',
        city: 'Santiago',
        region: 'Metropolitana',
        photos: [
          'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800',
          'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=800',
          'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800',
        ],
        coverPhoto: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800',
        status: 'APPROVED',
        views: 245,
        isPremium: true,
        viewCount: 245,
        isPromoted: false,
        availability: { lunes: '09:00-18:00', martes: '09:00-18:00', miercoles: '09:00-18:00' },
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'service-002',
        userId: 'publisher-001',
        category: 'MODELAJE',
        title: 'Book Fotográfico Completo',
        description: 'Book profesional completo con 3 looks diferentes, 50 fotos editadas y acceso a galería digital.',
        price: 150000,
        priceType: 'package',
        location: 'Estudio Las Condes',
        city: 'Santiago',
        region: 'Metropolitana',
        photos: [
          'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800',
          'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800',
        ],
        coverPhoto: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800',
        status: 'APPROVED',
        views: 189,
        isPremium: false,
        viewCount: 189,
        isPromoted: true,
        promotedUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        availability: { lunes: '10:00-19:00', martes: '10:00-19:00' },
        createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'service-003',
        userId: 'publisher-002',
        category: 'MASAJES_PROFESIONALES',
        title: 'Masaje Relajante Profesional',
        description: 'Masaje relajante de cuerpo completo con aceites esenciales. Ideal para liberar tensiones y estrés.',
        price: 45000,
        priceType: 'hour',
        location: 'Domicilio o Centro de Bienestar',
        city: 'Santiago',
        region: 'Metropolitana',
        photos: [
          'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
          'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800',
          'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800',
        ],
        coverPhoto: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
        status: 'APPROVED',
        views: 312,
        isPremium: true,
        viewCount: 312,
        isPromoted: false,
        availability: { lunes: '09:00-21:00', martes: '09:00-21:00', miercoles: '09:00-21:00', jueves: '09:00-21:00', viernes: '09:00-21:00' },
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'service-004',
        userId: 'publisher-002',
        category: 'MASAJES_PROFESIONALES',
        title: 'Masaje Deportivo Terapéutico',
        description: 'Masaje especializado para deportistas. Recuperación muscular, prevención de lesiones y mejora del rendimiento.',
        price: 55000,
        priceType: 'hour',
        location: 'Centro Deportivo Las Condes',
        city: 'Santiago',
        region: 'Metropolitana',
        photos: [
          'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=800',
          'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
        ],
        coverPhoto: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=800',
        status: 'APPROVED',
        views: 156,
        isPremium: false,
        viewCount: 156,
        isPromoted: false,
        availability: { lunes: '08:00-20:00', martes: '08:00-20:00', miercoles: '08:00-20:00' },
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'service-005',
        userId: 'publisher-003',
        category: 'MODELAJE',
        title: 'Modelaje para Eventos',
        description: 'Servicio de modelaje para eventos corporativos, lanzamientos de productos y promociones.',
        price: 100000,
        priceType: 'event',
        location: 'A convenir',
        city: 'Viña del Mar',
        region: 'Valparaíso',
        photos: [
          'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=800',
          'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800',
        ],
        coverPhoto: 'https://images.unsplash.com/photo-1496440737103-cd596325d314?w=800',
        status: 'PENDING',
        views: 0,
        isPremium: false,
        viewCount: 0,
        isPromoted: false,
        availability: { sabado: '10:00-22:00', domingo: '10:00-22:00' },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    reviews: [
      {
        id: 'review-001',
        serviceId: 'service-001',
        userId: 'user-001',
        rating: 5,
        comment: 'Excelente profesional, muy puntual y con gran actitud. Las fotos quedaron increíbles. Totalmente recomendada.',
        photos: [],
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'review-002',
        serviceId: 'service-003',
        userId: 'user-001',
        rating: 5,
        comment: 'El mejor masaje que he recibido. Carlos es muy profesional y realmente sabe lo que hace. Mi espalda quedó como nueva.',
        photos: [],
        response: 'Muchas gracias Juan! Me alegra mucho que hayas tenido una buena experiencia. Espero verte pronto.',
        respondedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'review-003',
        serviceId: 'service-002',
        userId: 'user-001',
        rating: 4,
        comment: 'Muy buen servicio, las fotos quedaron muy profesionales. Solo tardó un poco más de lo esperado.',
        photos: [],
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    posts: [
      {
        id: 'post-001',
        userId: 'publisher-001',
        content: '¡Nuevas fechas disponibles para sesiones fotográficas! Descuento del 20% en reservas para la próxima semana. 📸✨',
        type: 'PROMOTION',
        likes: 12,
        photos: ['https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800'],
        isPinned: true,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'post-002',
        userId: 'publisher-002',
        content: 'Recordatorio: Esta semana tengo horarios disponibles de lunes a viernes. ¡Reserva tu sesión de masaje relajante! 💆‍♂️',
        type: 'ANNOUNCEMENT',
        likes: 8,
        photos: [],
        isPinned: false,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'post-003',
        userId: 'publisher-001',
        content: '¡Gracias a todos mis clientes por su confianza! Ya son 100 sesiones fotográficas este año. 🎉',
        type: 'NEWS',
        likes: 25,
        photos: [],
        isPinned: false,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    favorites: [
      {
        id: 'fav-001',
        userId: 'user-001',
        serviceId: 'service-001',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'fav-002',
        userId: 'user-001',
        serviceId: 'service-003',
        createdAt: new Date().toISOString(),
      },
    ],
    notifications: [
      {
        id: 'notif-001',
        userId: 'publisher-001',
        title: 'Nueva reseña',
        message: 'Juan Pérez dejó una reseña de 5 estrellas en tu servicio.',
        type: 'review',
        isRead: false,
        link: '/services/service-001',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'notif-002',
        userId: 'publisher-002',
        title: 'Servicio aprobado',
        message: 'Tu servicio "Masaje Relajante Profesional" ha sido aprobado.',
        type: 'approval',
        isRead: true,
        link: '/services/service-003',
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    serviceTypes: [
      {
        id: 'type-001',
        name: 'MODELAJE',
        label: 'Modelaje',
        description: 'Servicios de modelaje profesional para fotografía, eventos y publicidad',
        icon: '📸',
        color: '#f97316',
        order: 1,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'type-002',
        name: 'MASAJES_PROFESIONALES',
        label: 'Masajes Profesionales',
        description: 'Servicios de masajes terapéuticos y relajantes certificados',
        icon: '💆',
        color: '#22c55e',
        order: 2,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    serviceUpdates: [
      {
        id: 'update-001',
        serviceId: 'service-001',
        type: 'PROMOTION',
        title: '¡Oferta especial!',
        content: '20% de descuento en sesiones esta semana',
        imageUrl: null,
        isActive: true,
        isPinned: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'update-002',
        serviceId: 'service-003',
        type: 'SCHEDULE',
        title: 'Nuevos horarios',
        content: 'Ahora atiendo también los sábados de 10:00 a 15:00',
        imageUrl: null,
        isActive: true,
        isPinned: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    metadataFields: [],
    userMetadata: [],
    customFieldValues: [],
  };

  fs.writeFileSync(dbPath, JSON.stringify(db, null, 2));
  console.log('✅ Base de datos temporal regenerada exitosamente!\n');
  console.log('📊 Datos creados:');
  console.log(`   - ${db.users.length} usuarios`);
  console.log(`   - ${db.services.length} servicios`);
  console.log(`   - ${db.reviews.length} reseñas`);
  console.log(`   - ${db.posts.length} posts`);
  console.log(`   - ${db.favorites.length} favoritos`);
  console.log(`   - ${db.notifications.length} notificaciones`);
  console.log(`   - ${db.serviceTypes.length} tipos de servicio`);
  console.log(`   - ${db.serviceUpdates.length} actualizaciones\n`);
  console.log('📝 Credenciales de prueba:');
  console.log('   Admin: admin@mipage.cl / password123');
  console.log('   Publisher 1: maria@example.com / password123');
  console.log('   Publisher 2: carlos@example.com / password123');
  console.log('   User: juan@example.com / password123\n');
}

regenerateDB().catch(console.error);
