import type { ProviderCardData } from '@/types'

export const mockProviders: ProviderCardData[] = [
  {
    id: '1',
    slug: 'valentina-reyes',
    display_name: 'Valentina Reyes',
    age: 28,
    city: 'Santiago',
    commune: 'Las Condes',
    category: 'masajes',
    is_verified: true,
    is_featured: true,
    average_rating: 4.9,
    review_count: 47,
    price_from: 45000,
    primary_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600',
  },
  {
    id: '2',
    slug: 'camila-silva',
    display_name: 'Camila Silva',
    age: 24,
    city: 'Santiago',
    commune: 'Providencia',
    category: 'modelaje',
    is_verified: true,
    is_featured: true,
    average_rating: 4.8,
    review_count: 32,
    price_from: 80000,
    primary_image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600',
  },
  {
    id: '3',
    slug: 'sofia-martinez',
    display_name: 'Sofía Martínez',
    age: 31,
    city: 'Viña del Mar',
    commune: null,
    category: 'masajes',
    is_verified: false,
    is_featured: false,
    average_rating: 4.7,
    review_count: 28,
    price_from: 40000,
    primary_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600',
  },
  {
    id: '4',
    slug: 'isabella-rojas',
    display_name: 'Isabella Rojas',
    age: 26,
    city: 'Santiago',
    commune: 'Ñuñoa',
    category: 'modelaje',
    is_verified: true,
    is_featured: false,
    average_rating: 4.9,
    review_count: 56,
    price_from: 75000,
    primary_image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600',
  },
  {
    id: '5',
    slug: 'carolina-paz',
    display_name: 'Carolina Paz',
    age: 29,
    city: 'Santiago',
    commune: 'Vitacura',
    category: 'masajes',
    is_verified: true,
    is_featured: false,
    average_rating: 4.6,
    review_count: 19,
    price_from: 55000,
    primary_image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600',
  },
  {
    id: '6',
    slug: 'fernanda-lopez',
    display_name: 'Fernanda López',
    age: 27,
    city: 'Concepción',
    commune: null,
    category: 'modelaje',
    is_verified: false,
    is_featured: false,
    average_rating: 4.5,
    review_count: 12,
    price_from: 60000,
    primary_image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600',
  },
]

export const featuredProviders = mockProviders.filter((p) => p.is_featured)

// filterCities / sortOptions live in @/lib/filters (product utils, not demo data)